In [1]:
from keras.preprocessing.text import one_hot

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good"
]


In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size = 10000

In [6]:
onehot_repr = [one_hot(words, voc_size) for words in sent]

In [8]:
onehot_repr # all the indexes of the words represented

[[3204, 3918, 570, 510],
 [3204, 3918, 570, 607],
 [3204, 6182, 570, 6587],
 [4093, 4178, 5050, 7424, 7345],
 [4093, 4178, 5050, 7424, 2384],
 [1988, 3204, 8541, 570, 777],
 [2807, 3040, 2972, 7424]]

In [9]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = "pre", maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 3204 3918  570  510]
 [   0    0    0    0 3204 3918  570  607]
 [   0    0    0    0 3204 6182  570 6587]
 [   0    0    0 4093 4178 5050 7424 7345]
 [   0    0    0 4093 4178 5050 7424 2384]
 [   0    0    0 1988 3204 8541  570  777]
 [   0    0    0    0 2807 3040 2972 7424]]


In [13]:
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile("adam", "mse")

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 71ms/step
[[[ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772
    0.03424538  0.04192431  0.02503434 -0.04668751  0.02595684]
  [ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772
    0.03424538  0.04192431  0.02503434 -0.04668751  0.02595684]
  [ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772
    0.03424538  0.04192431  0.02503434 -0.04668751  0.02595684]
  [ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772
    0.03424538  0.04192431  0.02503434 -0.04668751  0.02595684]
  [ 0.00881154 -0.00144093  0.02720338 -0.02248558  0.0158616
   -0.02458919 -0.0220526   0.01480544  0.04725549  0.00139724]
  [-0.02061599  0.03520894  0.00964526  0.02662888  0.01655092
    0.03097726 -0.02453469 -0.03161869  0.03189811  0.0324855 ]
  [ 0.03804822 -0.02929991  0.0055915   0.00810897 -0.02532681
   -0.0221355  -0.00215346  0.00607067  0.03540665 -0.04879247]
  [ 0.01330867  0.02991514 -0.03190231 -0.00438656 -0.010068

In [17]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 11ms/step
[[ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772  0.03424538
   0.04192431  0.02503434 -0.04668751  0.02595684]
 [ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772  0.03424538
   0.04192431  0.02503434 -0.04668751  0.02595684]
 [ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772  0.03424538
   0.04192431  0.02503434 -0.04668751  0.02595684]
 [ 0.02493883 -0.01293545  0.02490338  0.04371909 -0.04079772  0.03424538
   0.04192431  0.02503434 -0.04668751  0.02595684]
 [ 0.00881154 -0.00144093  0.02720338 -0.02248558  0.0158616  -0.02458919
  -0.0220526   0.01480544  0.04725549  0.00139724]
 [-0.02061599  0.03520894  0.00964526  0.02662888  0.01655092  0.03097726
  -0.02453469 -0.03161869  0.03189811  0.0324855 ]
 [ 0.03804822 -0.02929991  0.0055915   0.00810897 -0.02532681 -0.0221355
  -0.00215346  0.00607067  0.03540665 -0.04879247]
 [ 0.01330867  0.02991514 -0.03190231 -0.00438656 -0.01006844  0.0262241
 

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 3204, 3918,  570,  510])